-- TCX Supabase schema
-- Run in Supabase SQL editor before deploying functions.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.ea_instances (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  symbol text default 'XAUUSD',
  account_login text,
  token_hash text not null,
  enabled boolean not null default true,
  last_seen_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.ea_states (
  ea_id uuid primary key references public.ea_instances(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.commands (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  ea_id uuid not null references public.ea_instances(id) on delete cascade,
  client_id text,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','sent','done','failed','expired')),
  result_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  done_at timestamptz,
  expires_at timestamptz not null default (now() + interval '45 seconds')
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  ea_id uuid references public.ea_instances(id) on delete set null,
  action text not null,
  details jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_ea_instances_user_id on public.ea_instances(user_id);
create index if not exists idx_commands_ea_pending on public.commands(ea_id, status, created_at);
create index if not exists idx_commands_user_created on public.commands(user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.ea_instances enable row level security;
alter table public.ea_states enable row level security;
alter table public.commands enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists profiles_own on public.profiles;
create policy profiles_own on public.profiles for all using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists ea_instances_own_select on public.ea_instances;
create policy ea_instances_own_select on public.ea_instances for select using (user_id = auth.uid());
drop policy if exists ea_instances_own_insert on public.ea_instances;
create policy ea_instances_own_insert on public.ea_instances for insert with check (user_id = auth.uid());
drop policy if exists ea_instances_own_update on public.ea_instances;
create policy ea_instances_own_update on public.ea_instances for update using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists ea_instances_own_delete on public.ea_instances;
create policy ea_instances_own_delete on public.ea_instances for delete using (user_id = auth.uid());

drop policy if exists ea_states_own_select on public.ea_states;
create policy ea_states_own_select on public.ea_states for select using (user_id = auth.uid());

drop policy if exists commands_own_select on public.commands;
create policy commands_own_select on public.commands for select using (user_id = auth.uid());

drop policy if exists audit_own_select on public.audit_logs;
create policy audit_own_select on public.audit_logs for select using (user_id = auth.uid());

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
